name = "canthus-api"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Logging configuration
[observability]
enabled = true

# Environment variables for different environments
# For local development, create a .dev.vars file (see .dev.vars.example)
# For production, set secrets via: wrangler secret put SECRET_NAME

[vars]
NODE_ENV = "production"

# Environment-specific configurations
[env.development]
name = "canthus-api-dev"

[env.development.vars]
NODE_ENV = "development"

[env.staging]
name = "canthus-api-staging"

[env.staging.vars]
NODE_ENV = "staging"

# Secrets should be set via: wrangler secret put SECRET_NAME
# Required secrets:
# - WORKOS_API_KEY
# - WORKOS_CLIENT_ID  
# - WORKOS_REDIRECT_URI
# - WORKOS_COOKIE_PASSWORD
# - APP_BASE_URL

# Optional: Set up custom domain
# For custom domains, use the following format:
[env.production]
route = "api.canthus.org/*"
# 
# Or for zone-based routing:
# routes = [
#   { pattern = "api.canthus.org/*", zone_name = "canthus.org" }
# ]

[env.production.vars]
NODE_ENV = "production"

# Optional: Configure KV storage if needed for sessions
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
